<script lang="ts">
	import BellRing from 'lucide-svelte/icons/bell-ring';
	import Check from 'lucide-svelte/icons/check';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Switch } from '$lib/components/ui/switch/index.js';

	const notifications = [
		{
			title: 'Your call has been confirmed.',
			description: '1 hour ago'
		},
		{
			title: 'You have a new message!',
			description: '1 hour ago'
		},
		{
			title: 'Your subscription is expiring soon!',
			description: '2 hours ago'
		}
	];
</script>

<div class="">
	<div class="flex flex-row flex-wrap gap-4">
		<div class="flex flex-col">
			<Card.Root class="max-w-80">
				<Card.Header>
					<Card.Title>Proof of Work</Card.Title>
					<Card.Description>I have skills, and I want sats.</Card.Description>
				</Card.Header>
				<Card.Content class="grid gap-4">
					<div>
						<ul class="ml-6 list-disc [&>li]:mt-2">
							<li>Solve problems for fun and profit</li>
							<li>Get paid in Sats for every pull request</li>
							<li>No KYC, you only need an npub!</li>
						</ul>
					</div>
				</Card.Content>
				<Card.Footer>
					<Button class="w-full">Read more</Button>
				</Card.Footer>
			</Card.Root>
		</div>
		<div class="flex flex-col">
			<Card.Root class="max-w-80">
				<Card.Header>
					<Card.Title>Proof of Sats</Card.Title>
					<Card.Description>I have Sats, and I want a slice of a Rocket's satflow.</Card.Description
					>
				</Card.Header>
				<Card.Content class="grid gap-4">
					<div>
						<ul class="ml-6 list-disc [&>li]:mt-2">
							<li>Sponsor work that has already been done, and get equity in return</li>
							<li>
								Rockets are non-custodial, sats generated by Rockets go directly to equity holders
							</li>
							<li>No KYC, you only need an npub!</li>
						</ul>
					</div>
				</Card.Content>
				<Card.Footer>
					<Button class="w-full">Read more</Button>
				</Card.Footer>
			</Card.Root>
		</div>
		<div class="flex flex-col">
			<Card.Root class="max-w-80">
				<Card.Header>
					<Card.Title>Launch a new Rocket</Card.Title>
					<Card.Description
						>I have an open source project or product. I want other people to work on it with me,
						and/or I want sponsorship so I can dedicate myself to it.</Card.Description
					>
				</Card.Header>
				<Card.Content class="grid gap-4">
					<div>
						Bring your project or idea forward to a stage where you can quit your job and focus on
						what really matters, despite your lack of funding.
					</div>
				</Card.Content>
				<Card.Footer>
					<Button class="w-full">Read more</Button>
				</Card.Footer>
			</Card.Root>
		</div>
	</div>
</div>
