<script lang="ts">
	import BellRing from 'lucide-svelte/icons/bell-ring';
	import Check from 'lucide-svelte/icons/check';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Switch } from '$lib/components/ui/switch/index.js';
	import { base } from '$app/paths';

	const notifications = [
		{
			title: 'Your call has been confirmed.',
			description: '1 hour ago'
		},
		{
			title: 'You have a new message!',
			description: '1 hour ago'
		},
		{
			title: 'Your subscription is expiring soon!',
			description: '2 hours ago'
		}
	];
</script>

<div class="">
	<div class="flex flex-row flex-wrap gap-4">
		<div class="flex flex-col">
			<Card.Root class="max-w-80">
				<Card.Header>
					<Card.Title>Proof of Work</Card.Title>
					<Card.Description>I have skills and I'm ready to work for sats.</Card.Description>
				</Card.Header>
        <img src="{base}/a.png" />
				<Card.Content class="grid gap-4">
					<div>
						<ul class="ml-6 list-disc [&>li]:mt-2">
							<li>Solve problems for fun and profit</li>
							<li>Get paid in Sats for every pull request</li>
							<li>No KYC. You only need an npub!</li>
						</ul>
					</div>
				</Card.Content>
				<Card.Footer>
					<Button class="w-full">Read more</Button>
				</Card.Footer>
			</Card.Root>
		</div>
		<div class="flex flex-col">
			<Card.Root class="max-w-80">
				<Card.Header>
					<Card.Title>Proof of Sats</Card.Title>
					<Card.Description>I have Sats, and I want a slice of a Rocket's satflow.</Card.Description
					>
				</Card.Header>
        <img src="{base}/scrooge.png" width="100%" />
				<Card.Content class="grid gap-4">
					<div>
						<ul class="ml-6 list-disc [&>li]:mt-2">
							<li>Sponsor merged pull requests and get equity in return</li>
							<li>
								Rockets are non-custodial, sats generated by Rockets go directly to equity holders
							</li>
							<li>No KYC, you only need an npub!</li>
						</ul>
					</div>
				</Card.Content>
				<Card.Footer>
					<Button class="w-full">Read more</Button>
				</Card.Footer>
			</Card.Root>
		</div>
		<div class="flex flex-col">
			<Card.Root class="max-w-80">
				<Card.Header>
					<Card.Title>Launch a new Rocket</Card.Title>
					<Card.Description
						>I'm working on my own project and I want other people to join me.</Card.Description
					>
				</Card.Header>
        <img src="{base}/rocket.jpg" width="100%" />
				<Card.Content class="grid gap-4">
					<div>
            <ul class="ml-6 list-disc [&>li]:mt-2">
							<li>Hire people to help build your project, despite your lack of funding</li>
							<li>
								Make your project resistant to parasites and grifters
							</li>
							<li>No KYC, you only need an npub!</li>
						</ul>
					</div>
				</Card.Content>
				<Card.Footer>
					<Button class="w-full">Read more</Button>
				</Card.Footer>
			</Card.Root>
		</div>
	</div>
</div>
